version: '3.8'

networks:
  laravel:
    name: laravel
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    networks:
      - laravel
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
  php:
    container_name: php
    build:
      context: .
      dockerfile: php.dockerfile
    networks:
      - laravel
    volumes:
      - ./src:/var/www/html
  mysql:
    container_name: mysql
    image: mysql:5.7.32
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel